# Site settings
title: RxUx
email: rich@sollenne.com
description: > # this means to ignore newlines until "baseurl:"
  No Description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: richsollenne
github_username:  sollenne
sass:
  sass_dir: _sass
# Build settings
markdown: kramdown
