# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: E-commerce Style Guide
email: Rich@Sollenne.com
description: > #
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rxux.github.io" # the base hostname & protocol for your site
twitter_username: richsollenne
github_username:  sollenne
safe: false

  # Build settings
markdown: kramdown

contentful:
  spaces:
    - links:
        space: d9ue08nhxkkm
        access_token: 7c18b3ed7eb6b7e20633fb2f12919c13358a1176fa52fe0ee551a2a690022da9
        content_types:
          link: MyReverseMapper
